### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by phaethix** [OriginGentle/hero_story.go_server#1]
How can I contact you? Can I have a private chat?

**Comment by turbo77-yang** [comment]
邮件已收到。

**Comment by aldalee** [comment]
加个微信聊吧，MarxLee_ 


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年7月12日 12:25 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [OriginGentle/hero_story.go_server] 请假问题 (Issue #1) |

邮件已收到。

**Comment by aldalee** [comment]
1
